// Copyright 2026 reBot ros2_control contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef REBOT_CONTROLLERS__GRAVITY_COMPENSATION_CONTROLLER_HPP_
#define REBOT_CONTROLLERS__GRAVITY_COMPENSATION_CONTROLLER_HPP_

#include <memory>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "realtime_tools/realtime_publisher.h"
#include "std_msgs/msg/float64_multi_array.hpp"

#include "rebot_controllers/kdl_gravity.hpp"
#include "rebot_controllers/mit_interface_helpers.hpp"

// auto-generated by generate_parameter_library
#include "gravity_compensation_controller_parameters.hpp"

namespace rebot_controllers
{

/// Zero-gravity / hand-guiding mode: kp = 0, kd = small damping,
/// effort = clamp(scale * g(q)). g(q) comes from the URDF via KDL
/// (ChainDynParam), per-joint clamped to a fraction of the rated torque.
/// The computed torques are published on ~/gravity_torques for verification.
class GravityCompensationController : public controller_interface::ControllerInterface
{
public:
  controller_interface::CallbackReturn on_init() override;
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;
  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::return_type update(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

protected:
  std::shared_ptr<gravity_compensation_controller::ParamListener> param_listener_;
  gravity_compensation_controller::Params params_;

  KdlGravity gravity_;
  std::vector<double> positions_;
  std::vector<double> gravity_torques_;

  using TorqueMsg = std_msgs::msg::Float64MultiArray;
  rclcpp::Publisher<TorqueMsg>::SharedPtr torque_pub_;
  std::unique_ptr<realtime_tools::RealtimePublisher<TorqueMsg>> rt_torque_pub_;

  MitCommandHandles command_handles_;
  JointStateHandles state_handles_;
};

}  // namespace rebot_controllers

#endif  // REBOT_CONTROLLERS__GRAVITY_COMPENSATION_CONTROLLER_HPP_
