// Copyright 2026 reBot ros2_control contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef REBOT_CONTROLLERS__JOINT_IMPEDANCE_CONTROLLER_HPP_
#define REBOT_CONTROLLERS__JOINT_IMPEDANCE_CONTROLLER_HPP_

#include <memory>
#include <string>
#include <vector>

#include "controller_interface/chainable_controller_interface.hpp"
#include "realtime_tools/realtime_buffer.h"
#include "std_msgs/msg/float64_multi_array.hpp"

#include "rebot_controllers/kdl_gravity.hpp"
#include "rebot_controllers/mit_interface_helpers.hpp"

// auto-generated by generate_parameter_library
#include "joint_impedance_controller_parameters.hpp"

namespace rebot_controllers
{

/// Chainable joint impedance controller. Exports one position reference
/// interface per joint (<controller>/<joint>/position); when not chained it
/// subscribes to ~/reference (Float64MultiArray, joint order = `joints`).
///
/// Two modes (parameter `mode`):
///  - "onboard"  (default): stiffness/damping run in the motor's MIT loop
///    (p_des = q_ref, kp = K, kd = D, t_ff = g(q)); insensitive to the
///    controller_manager rate.
///  - "software": motor gains are zero and the impedance law closes here:
///    t_ff = K (q_ref - q) + D (0 - q_dot) + g(q); limited by the 100 Hz
///    update rate but free of the MIT gain encoding ranges.
class JointImpedanceController : public controller_interface::ChainableControllerInterface
{
public:
  controller_interface::CallbackReturn on_init() override;
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;
  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;

protected:
  std::vector<hardware_interface::CommandInterface> on_export_reference_interfaces() override;
  controller_interface::return_type update_reference_from_subscribers() override;
  controller_interface::return_type update_and_write_commands(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

  std::shared_ptr<joint_impedance_controller::ParamListener> param_listener_;
  joint_impedance_controller::Params params_;
  bool software_mode_{false};

  rclcpp::Subscription<std_msgs::msg::Float64MultiArray>::SharedPtr reference_sub_;
  realtime_tools::RealtimeBuffer<std::shared_ptr<std::vector<double>>> reference_buffer_;

  KdlGravity gravity_;
  bool use_gravity_ff_{false};
  std::vector<double> q_;
  std::vector<double> qd_;
  std::vector<double> g_tau_;

  MitCommandHandles command_handles_;
  JointStateHandles state_handles_;
};

}  // namespace rebot_controllers

#endif  // REBOT_CONTROLLERS__JOINT_IMPEDANCE_CONTROLLER_HPP_
