// Copyright 2026 reBot ros2_control contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef REBOT_CONTROLLERS__MIT_JOINT_CONTROLLER_HPP_
#define REBOT_CONTROLLERS__MIT_JOINT_CONTROLLER_HPP_

#include <memory>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "realtime_tools/realtime_buffer.h"

#include "rebot_controllers/mit_interface_helpers.hpp"
#include "rebot_msgs/msg/mit_joint_command.hpp"

// auto-generated by generate_parameter_library
#include "mit_joint_controller_parameters.hpp"

namespace rebot_controllers
{

/// MIT-mode passthrough controller: forwards the full Damiao five-tuple
/// (position, velocity, kp, kd, effort) from a rebot_msgs/MitJointCommand
/// topic to the hardware through a RealtimeBuffer. Capability base for the
/// rest of the stack (see docs/controllers_design.md).
class MitJointController : public controller_interface::ControllerInterface
{
public:
  controller_interface::CallbackReturn on_init() override;
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;
  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::return_type update(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

protected:
  /// One reordered, validated command set (written by the subscriber
  /// callback in the non-RT thread, consumed by update()).
  struct Command
  {
    std::vector<double> position;
    std::vector<double> velocity;
    std::vector<double> kp;
    std::vector<double> kd;
    std::vector<double> effort;
    rclcpp::Time stamp;
  };

  void command_callback(const rebot_msgs::msg::MitJointCommand & msg);

  std::shared_ptr<mit_joint_controller::ParamListener> param_listener_;
  mit_joint_controller::Params params_;

  rclcpp::Subscription<rebot_msgs::msg::MitJointCommand>::SharedPtr command_sub_;
  realtime_tools::RealtimeBuffer<std::shared_ptr<Command>> command_buffer_;

  MitCommandHandles command_handles_;
  JointStateHandles state_handles_;
};

}  // namespace rebot_controllers

#endif  // REBOT_CONTROLLERS__MIT_JOINT_CONTROLLER_HPP_
