// Copyright 2026 reBot ros2_control contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef REBOT_CONTROLLERS__TELEOP_STREAM_CONTROLLER_HPP_
#define REBOT_CONTROLLERS__TELEOP_STREAM_CONTROLLER_HPP_

#include <memory>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "realtime_tools/realtime_buffer.h"
#include "std_msgs/msg/float64_multi_array.hpp"

#include "rebot_controllers/mit_interface_helpers.hpp"
#include "rebot_controllers/rate_limiter.hpp"

// auto-generated by generate_parameter_library
#include "teleop_stream_controller_parameters.hpp"

namespace rebot_controllers
{

/// Streaming teleoperation controller: follows a high-rate target position
/// stream (~/commands, Float64MultiArray in joint order) through a
/// velocity/acceleration-bounded online smoother. When the stream stalls for
/// longer than `command_timeout` the target latches onto the current
/// smoothed position and kd is raised (`timeout_kd_scale`) for extra
/// damping until commands resume.
class TeleopStreamController : public controller_interface::ControllerInterface
{
public:
  controller_interface::CallbackReturn on_init() override;
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;
  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::return_type update(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;

protected:
  struct StampedTarget
  {
    std::vector<double> positions;
    rclcpp::Time stamp;
  };

  std::shared_ptr<teleop_stream_controller::ParamListener> param_listener_;
  teleop_stream_controller::Params params_;

  rclcpp::Subscription<std_msgs::msg::Float64MultiArray>::SharedPtr command_sub_;
  realtime_tools::RealtimeBuffer<std::shared_ptr<StampedTarget>> target_buffer_;

  std::vector<RateLimiter> limiters_;
  std::vector<double> smoothed_;   ///< current smoothed command
  std::vector<double> target_;     ///< latched target
  bool timed_out_{false};

  MitCommandHandles command_handles_;
  JointStateHandles state_handles_;
};

}  // namespace rebot_controllers

#endif  // REBOT_CONTROLLERS__TELEOP_STREAM_CONTROLLER_HPP_
